# Generated by Django 4.2.1 on 2023-05-26 05:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alcohols', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alcohol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('desc', models.CharField(max_length=256)),
                ('volt', models.IntegerField()),
                ('votes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AlcoholType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('alcohol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alcohols.alcohol')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fav_alcohols', models.ManyToManyField(to='alcohols.alcohol')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('desc', models.CharField(max_length=256)),
            ],
        ),
        migrations.DeleteModel(
            name='Beers',
        ),
        migrations.DeleteModel(
            name='Vodka',
        ),
        migrations.DeleteModel(
            name='Wines',
        ),
        migrations.AddField(
            model_name='alcohol',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alcohols.alcoholtype'),
        ),
    ]
