# Generated by Django 4.2.1 on 2023-05-31 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alcohols', '0004_wines'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wines',
        ),
    ]
