# Generated by Django 4.2.1 on 2023-05-31 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alcohols', '0007_rename_wine_alcohols_wine'),
    ]

    operations = [
        migrations.DeleteModel(
            name='alcohols_wine',
        ),
    ]
