# Generated by Django 4.2.1 on 2023-05-31 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alcohols', '0008_delete_alcohols_wine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alcohol', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='alcohols.alcohol')),
                ('dryness', models.CharField(choices=[('dry', 'Dry'), ('semi-dry', 'Semi-Dry'), ('sweet', 'Sweet')], max_length=10)),
                ('color', models.CharField(choices=[('red', 'Red'), ('white', 'White'), ('rose', 'Rosé')], max_length=10)),
            ],
        ),
    ]
