# Generated by Django 4.2.1 on 2023-05-31 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alcohols', '0012_rename_alcohol_comment_alc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wine',
        ),
    ]
