# Generated by Django 4.2.1 on 2023-06-01 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcohols', '0018_alter_comment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
