# Generated by Django 4.2.1 on 2023-06-01 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alcohols', '0019_alter_comment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='fav_alcohols',
            new_name='fav_alcohos',
        ),
    ]
