# Generated by Django 4.2.1 on 2023-06-01 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alcohols', '0020_rename_fav_alcohols_userprofile_fav_alcohos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='fav_alcohos',
        ),
    ]
