# Generated by Django 4.2.1 on 2023-06-01 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alcohols', '0022_remove_userprofile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
