# Generated by Django 4.2.1 on 2023-06-01 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alcohols', '0024_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
